buddyread/books/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("nieuwe/", views.add_or_edit_club, name="add_club"),
    path("keuze/", views.choose_club, name="choose_club"),
    path("uitnodiging/<str:url_uuid>/", views.sign_up, name="sign_up"),
    path("beheer/", views.club_overview, name="club_overview"),
    path("beheer/<slug:club>/", views.club_custom_admin, name="club_custom_admin"),
    path("beheer/<slug:club>/wijzig/", views.add_or_edit_club, name="edit_club"),
    path("beheer/<slug:club>/verwijder/", views.delete_club, name="delete_club"),
    path("beheer/<slug:club>/verwijder/lid/<int:member_pk>", views.delete_club_member, name="delete_club_member"),
    path("beheer/<slug:club>/verwijder/boek/<int:book_pk>", views.delete_club_book, name="delete_club_book"),
    path("beheer/<slug:club>/rechten/lid/<int:member_pk>", views.grant_mod_perm, name="grant_mod_perm"),
    path("beheer/<slug:club>/uitnodigen/lid/", views.invite_member, name="invite_member"),
    path("<slug:club>/", views.books, name="books"),
    path("<slug:club>/add/boek/", views.add_book, name="add_book"),
    path("<slug:club>/review/<int:book_pk>/", views.review, name="review"),
]

buddyread/buddyread/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("club/", include("books.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

buddyread/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("profiel/", views.change_auth, name="change_auth")
]

buddyread/books/models.py
from datetime import datetime, timedelta
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
from django.utils import timezone


class Book(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    author = models.CharField(max_length=255, blank=False, null=False)
    creation_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    SCORES = [
        ('DNF', 'DNF'),
        ('1', '1'),
        ('1.5', '1.5'),
        ('2', '2'),
        ('2.5', '2.5'),
        ('3', '3'),
        ('3.5', '3.5'),
        ('4', '4'),
        ('4.5', '4.5'),
        ('5', '5'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    score = models.CharField(
        max_length=3,
        blank=False,
        null=False,
        choices=SCORES
    )
    comment = models.TextField(blank=True, null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'book'], name='unique_user_book')
        ]

    def __str__(self):
        return f"{self.book.title} - {self.user.username}"


class BookClub(models.Model):
    slug = models.SlugField(primary_key=True, max_length=50, null=False, blank=False)
    name = models.CharField(unique=True, max_length=50, null=False, blank=False)
    creation_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


class BookClubMembers(models.Model):
    book_club = models.ForeignKey(BookClub, on_delete=models.CASCADE, blank=False, null=False)
    member = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    is_mod = models.BooleanField(blank=False, null=False, default=False)

    class Meta:
        verbose_name_plural = "Book club members"


class BookClubBooks(models.Model):
    book_club = models.ForeignKey(BookClub, on_delete=models.CASCADE, blank=False, null=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=False, null=False)
    selected_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date_added = models.DateField(auto_now_add=True, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Book club books"


class InviteURL(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    creation_date = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(blank=False, null=False, default=False)
    book_club = models.ForeignKey(BookClub, on_delete=models.CASCADE, blank=False, null=False)


    def is_expired(self):
        expiration_time = self.creation_date + timedelta(days=1)
        return timezone.now() >= expiration_time

buddyread/books/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from .models import Book, Review, BookClub


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author"]
        labels = {
            "title": "Titel",
            "author": "Auteur"
        }

    helper = FormHelper()
    helper.add_input(Submit('submit', 'Opslaan', css_class='btn-primary'))
    helper.form_method = 'POST'


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["score", "comment"]
        labels = {
            "score": "Score",
            "comment": "Commentaar"
        }

    helper = FormHelper()
    helper.add_input(Submit('submit', 'Opslaan', css_class='btn-primary'))
    helper.form_method = 'POST'


class BookClubForm(forms.ModelForm):
    class Meta:
        model = BookClub
        fields = ["name"]
        labels = {
            "name": "Naam",
        }

    helper = FormHelper()
    helper.add_input(Submit('submit', 'Opslaan', css_class='btn-primary'))
    helper.form_method = 'POST'


class ConfirmDeleteForm(forms.Form):
    confirm = forms.BooleanField(
        required=True,
        label="Ik bevestig dat het bovenstaande onderdeel wordt verwijderd."
    )

    helper = FormHelper()
    helper.add_input(Submit('submit', 'Verwijder', css_class='btn-danger'))
    helper.form_method = 'POST'


class ConfirmModeratorForm(forms.Form):
    confirm = forms.BooleanField(
        required=True,
        label="Ik bevestig dat bovenstaande lid beheerrechten krijgt."
    )

    helper = FormHelper()
    helper.add_input(Submit('submit', 'Opslaan', css_class='btn-primary'))
    helper.form_method = 'POST'


class InviteMemberForm(forms.Form):

    username = forms.CharField(max_length=255, label="Gebruikersnaam")
    password = forms.CharField(widget=forms.PasswordInput, required=False, label="Wachtwoord")
    password_repeat = forms.CharField(widget=forms.PasswordInput, required=False, label="Herhaal wachtwoord")

    helper = FormHelper()
    helper.add_input(Submit('submit', 'Opslaan', css_class='btn-primary'))
    helper.form_method = 'POST'


    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data["username"]

        if get_user_model().objects.filter(username=username).exists():
            raise ValidationError('Er bestaat al een gebruiker met deze gebruikersnaam')

        password = cleaned_data["password"]
        password_repeat = cleaned_data["password_repeat"]
        if password != password_repeat:
            raise ValidationError('Het wachtwoord en de herhaling komen niet overeen')

buddyread/books/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.db.models import Prefetch
from .models import Book, Review, BookClub, BookClubMembers, BookClubBooks, InviteURL
from .forms import BookForm, ReviewForm, BookClubForm, ConfirmDeleteForm, ConfirmModeratorForm, InviteMemberForm
from .decorators import user_is_club_member, user_is_club_mod


@login_required
def add_or_edit_club(request, club=None):
    book_club = None
    form_caption = "Start een nieuwe boekenclub!"

    if club is not None:
        book_club = get_object_or_404(BookClub, slug=club)
        member = get_object_or_404(BookClubMembers, book_club=book_club, member=request.user)

        if not member.is_mod:
            return HttpResponseForbidden(
                f"Geen recht om boekenclub '{book_club.name}' te wijzigen"
            )

        form_caption = "Wijzig boekenclub"

    if request.method == "POST":
        form = BookClubForm(request.POST, instance=book_club)
        if form.is_valid():
            book_club = form.save()

            if club is None:
                BookClubMembers.objects.create(
                    book_club=book_club, member=request.user, is_mod=True
                )

            return redirect("books", club=book_club.slug)

    else:
        form = BookClubForm(instance=book_club)

    return render(request, "books/generic_form.html", {
        'form': form,
        'form_caption': form_caption
    })


@login_required
@user_is_club_mod
def delete_club(request, club):
    book_club = get_object_or_404(BookClub, slug=club)
    if request.method == "POST":
        form = ConfirmDeleteForm(request.POST)
        if form.is_valid():
            book_club.delete()
            return redirect('club_overview')
    else:
        form = ConfirmDeleteForm()
    context = {
        'form': form,
        'form_caption': f"Verwijder boekenclub '{book_club.name}' en alle gerelateerde gegevens",
    }
    return render(request, "books/generic_form.html", context)


@login_required
def choose_club(request):
    book_clubs = [
        m.book_club
        for m in BookClubMembers.objects.filter(member=request.user)
    ]
    context = {'book_clubs': book_clubs}
    return render(request, "books/choose_club.html", context)


@login_required
@user_is_club_member
def books(request, club):
    book_club = get_object_or_404(BookClub, slug=club)
    book_club_books = BookClubBooks.objects.filter(book_club=book_club)
    book_clubs = [
        m.book_club
        for m in BookClubMembers.objects.filter(member=request.user)
        if m.book_club != book_club
    ]

    book_qs = book_club_books.select_related("book").prefetch_related(
            Prefetch(
                "book__review_set",
                queryset=Review.objects.filter(
                    user__in=book_club.bookclubmembers_set.values("member")
                )
            )
        ).order_by('-date_added')
    context = {"books": book_qs, "club": book_club, "book_clubs": book_clubs}
    return render(request, "books/book_list.html", context)


@login_required
@user_is_club_member
def add_book(request, club):
    book_club = get_object_or_404(BookClub, slug=club)
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            book, created = Book.objects.get_or_create(
                title=title,
                author=author,
            )
            BookClubBooks.objects.create(
                book_club=book_club,
                book=book,
                selected_by=request.user,
            )
            return redirect('books', club=book_club.slug)
    else:
        form = BookForm()
    context = {
        'form': form,
        'form_caption': f"Voeg een boek toe aan {book_club.name}",
        'club': book_club.name
    }
    return render(request, "books/generic_form.html", context)


@login_required
@user_is_club_member
def review(request, club, book_pk):
    book = get_object_or_404(Book, pk=book_pk)
    book_club = get_object_or_404(BookClub, slug=club)
    review_selected = Review.objects.filter(user=request.user, book=book).first()
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            score = form.cleaned_data['score']
            comment = form.cleaned_data['comment']
            if review_selected is None:
                Review.objects.create(
                    user=request.user,
                    book=book,
                    score=score,
                    comment=comment
                )
            else:
                review_selected.score=score
                review_selected.comment=comment
                review_selected.save()
            return redirect('books', club=book_club.slug)
    else:
        if review_selected is None:
            form = ReviewForm()
        else:
            initial_data = {
                'score': review_selected.score,
                'comment': review_selected.comment
            }
            form = ReviewForm(initial=initial_data)
    context = {'book': book, 'form': form}
    return render(request, "books/review_form.html", context)

@login_required
def club_overview(request):
    book_clubs = BookClubMembers.objects.filter(member=request.user)
    context = {'book_clubs': book_clubs}
    return render(request, "books/club_overview.html", context)


@login_required
@user_is_club_mod
def club_custom_admin(request, club):
    book_club = get_object_or_404(BookClub, slug=club)
    context = {
        "book_club": book_club,
        "members": BookClubMembers.objects.filter(book_club=book_club),
        "club_books": BookClubBooks.objects.filter(book_club=book_club)
    }
    return render(request, "books/club_custom_admin.html", context)


@login_required
@user_is_club_mod
def delete_club_member(request, club, member_pk):
    book_club = get_object_or_404(BookClub, slug=club)
    club_member = get_object_or_404(BookClubMembers, book_club=book_club, pk=member_pk)
    if request.method == "POST":
        form = ConfirmDeleteForm(request.POST)
        if form.is_valid():
            club_member.delete()
            return redirect("club_custom_admin", club=book_club.slug)
    else:
        if club_member.is_mod:
            return redirect("club_custom_admin", club=book_club.slug)
        form = ConfirmDeleteForm()
    context = {
        'form': form,
        'form_caption': f"Verwijder lid '{club_member.member.username}' en alle gerelateerde gegevens uit '{book_club.name}'",
    }
    return render(request, "books/generic_form.html", context)


@login_required
@user_is_club_mod
def delete_club_book(request, club, book_pk):
    book_club = get_object_or_404(BookClub, slug=club)
    club_book = get_object_or_404(BookClubBooks, book_club=book_club, pk=book_pk)
    if request.method == "POST":
        form = ConfirmDeleteForm(request.POST)
        if form.is_valid():
            club_book.delete()
            return redirect("club_custom_admin", club=book_club.slug)
    else:
        form = ConfirmDeleteForm()
    context = {
        'form': form,
        'form_caption': f"Verwijder boek '{club_book.book.title}' en alle gerelateerde gegevens uit '{book_club.name}'",
    }
    return render(request, "books/generic_form.html", context)


@login_required
@user_is_club_mod
def grant_mod_perm(request, club, member_pk):
    book_club = get_object_or_404(BookClub, slug=club)
    club_member = get_object_or_404(BookClubMembers, book_club=book_club, pk=member_pk)
    if request.method == "POST":
        form = ConfirmModeratorForm(request.POST)
        if form.is_valid():
            club_member.is_mod = True
            club_member.save()
            return redirect("club_custom_admin", club=book_club.slug)
    else:
        if club_member.is_mod:
            return redirect("club_custom_admin", club=book_club.slug)
        form = ConfirmModeratorForm()
    context = {
        'form': form,
        'form_caption': f"Geef het lid '{club_member.member.username}' recht om '{book_club.name}' te beheren",
    }
    return render(request, "books/generic_form.html", context)


@login_required
@user_is_club_mod
def invite_member(request, club):
    book_club = get_object_or_404(BookClub, slug=club)
    invite_url = InviteURL.objects.create(book_club=book_club)
    url = reverse('sign_up', kwargs={'url_uuid': invite_url.uuid})
    context = {
        'book_club': book_club,
        'invite_url': request.build_absolute_uri(url)
    }
    return render(request, "books/invite_member.html", context)


def sign_up(request, url_uuid):
    invite_url = InviteURL.objects.get(uuid=url_uuid)
    book_club = get_object_or_404(BookClub, slug=invite_url.book_club.slug)

    if invite_url.accepted or invite_url.is_expired():
        return HttpResponseForbidden("Uitnodiging is verlopen")

    if request.method == "POST":
        form = InviteMemberForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            new_user = get_user_model().objects.create_user(username=username, password=password)
            BookClubMembers.objects.create(book_club=book_club, member=new_user)
            invite_url.accepted=True
            invite_url.save()
            return redirect("index")

    else:
        form = InviteMemberForm()

    context = {
        'form': form,
        'form_caption': f"Wordt lid bij boekenclub: {book_club.name}",
    }
    return render(request, "books/generic_form.html", context)

buddyread/books/templates/books/add_club.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card m-5">
    <div class="card-body">
        <h3 class="mb-3">Start een nieuwe boeken club!</h3>
        {% crispy form %}
    </div>
</div>
{% endblock %}

buddyread/books/templates/books/book_list.html
{% extends "core/index.html" %}
{% load review_tags %}

{% block content %}
<div class="card m-5">
<div class="card-header d-flex align-items-center justify-content-between">
    <a class="btn btn-success" href="{% url 'add_book' club=club.slug %}" role="button">
        <i class="bi bi-book-half"></i> <i class="bi bi-plus-square"></i>
    </a>

    {% if book_clubs|length > 0 %}
        <div class="dropdown ms-auto">
            <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                {{ club.name }}
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
                {% for book_club in book_clubs %}
                    <li><a class="dropdown-item" href="{% url 'books' club=book_club.slug %}">{{ book_club.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <span class="ms-auto">{{ club.name }}</span>
    {% endif %}
</div>

    <div class="card-body">
        <div class="list-group">
            {% for book in books %}
            <a href="{% url 'review' club=club.slug book_pk=book.book.pk %}" class="list-group-item list-group-item-action mb-3 border {% if forloop.counter == 1 %}active{% endif %}" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ book.book.title }} ({{ book.selected_by}}'s keuze)</h5>
                  <small>Toegevoegd op {{ book.date_added|date:"SHORT_DATE_FORMAT"  }}</small>
                </div>
                <p class="mb-1">{{ book.book.author }}</p>
                {% if book.book.review_set.all %}
                <div class="mt-2 {% if forloop.counter == 1 %}text-white{% else %}text-muted{% endif %}">
                    <small class="d-block mb-1">Reviews:</small>
                    <div class="ps-2">
                        {% for review in book.book.review_set.all %}
                            <p class="mb-1 small">
                                <strong>{{ review.user.username }}</strong>: {{ review.score|stars }}<br>
                                <span class="fst-italic">{{ review.comment|default:"" }}</span>
                            </p>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

buddyread/books/templates/books/choose_club.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card m-5">
    <div class="card-body">
        <h3 class="mb-3">Er zijn meerdere boekenclubs waarvan u lid bent</h3>
        <div class="dropdown">
            <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                Kies een boeken club
            </button>
            <ul class="dropdown-menu">
                {% for club in book_clubs %}
                    <li><a class="dropdown-item" href="{% url 'books' club=club.slug %}">{{ club.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

buddyread/books/templates/books/club_custom_admin.html
{% extends "core/index.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card m-5 w-50">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span>Boeken club: {{ book_club.name }}</span>

        <div class="btn-group">
            <a href="{% url 'edit_club' club=book_club.slug%}" type="button" class="btn btn-outline-secondary btn-sm">
                <i class="bi bi-pencil"></i>
            </a>
            <a href="{% url 'delete_club' club=book_club.slug%}" type="button" class="btn btn-outline-danger btn-sm">
                <i class="bi bi-trash"></i>
            </a>
        </div>
    </div>


        <div class="card-body">
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Leden
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <ul class="list-group">
                                {% for m in members %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div>
                                        {{ m.member.username }}
                                        {% if m.is_mod %}
                                        <span class="badge bg-info rounded-pill">Beheerder</span>
                                        {% endif %}
                                    </div>
                                    <div class="btn-group">
                                        <a href="{% url 'grant_mod_perm' club=book_club.slug member_pk=m.pk %}" type="button" class="btn btn-outline-primary btn-sm">
                                            <i class="bi bi-person-gear"></i>
                                        </a>
                                        <a href="{% url 'delete_club_member' club=book_club.slug member_pk=m.pk %}" type="button" class="btn btn-outline-danger btn-sm">
                                            <i class="bi bi-trash"></i>
                                        </a>
                                    </div>
                                </li>
                                {% endfor %}
                                <li class="list-group-item">
                                    <a href="{% url 'invite_member' club=book_club.slug %}" type="button" class="btn btn-outline-success">
                                        <i class="bi bi-person-add"></i> Lid uitnodigen
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Boeken
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <ul class="list-group">
                                {% for b in club_books %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div>
                                        {{ b.book.title }}, {{ b.book.author }}
                                    </div>
                                    <a href="{% url 'delete_club_book' club=book_club.slug book_pk=b.pk %}" type="button" class="btn btn-outline-danger btn-sm">
                                        <i class="bi bi-trash"></i>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

buddyread/books/templates/books/club_overview.html
{% extends "core/index.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card m-5 w-50">
        <div class="card-header d-flex align-items-center justify-content-between">
            Mijn boekenclubs
            <a class="btn btn-success" href="{% url 'add_club' %}" role="button">
                <i class="bi bi-journal-plus"></i>
            </a>
        </div>

        <div class="card-body">
            <div class="list-group">
                {% for club in book_clubs %}
                {% if club.is_mod %}
                <a href="{% url 'club_custom_admin' club=club.book_club.slug %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                    {{ club.book_club.name }}
                    <span class="badge bg-info rounded-pill">Beheerder</span>
                </a>
                {% else %}
                <a href="#" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                    {{ club.book_club.name }}
                    <span class="badge bg-info rounded-pill">Lid</span>
                </a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

buddyread/books/templates/books/generic_form.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card m-5">
    <div class="card-body">
        <h3 class="mb-3">{{ form_caption }}</h3>
        {% crispy form %}
    </div>
</div>
{% endblock %}

buddyread/books/templates/books/invite_member.html
{% extends "core/index.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card m-5 w-50">
        <div class="card-header d-flex justify-content-between align-items-center">
            <span>Boeken club: {{ book_club.name }}</span>
        </div>

        <div class="card-body">
            Stuur de onderstaande link naar iemand toe om hem/haar uit te nodigen voor de boekenclub.<br><br>

            <div class="input-group">
                <input id="inviteLink" type="text" class="form-control" value="{{ invite_url }}" readonly>
                <button class="btn btn-outline-secondary" type="button" onclick="copyInviteLink()"><i class="bi bi-clipboard"></i></button>
            </div>

            <br>

            <strong>Let op</strong>: De link is uiterlijk 1 dag geldig en is eenmalig te gebruiken.<br><br>

            <a href="{% url 'invite_member' club=book_club.slug %}" type="button" class="btn btn-success">
                Genereer een nieuwe URL
            </a>
            <a href="{% url 'club_custom_admin' club=book_club.slug %}" type="button" class="btn btn-secondary">
                Terug naar beheer
            </a>
        </div>
    </div>
</div>

<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="copyToast" class="toast text-bg-success" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                Link gekopieerd!
            </div>
        </div>
    </div>
</div>

<script>
function copyInviteLink() {
    const field = document.getElementById("inviteLink");

    navigator.clipboard.writeText(field.value)
        .then(() => {
            const toastEl = document.getElementById('copyToast');
            const toast = new bootstrap.Toast(toastEl);
            toast.show();
        })
}
</script>

{% endblock %}

buddyread/books/templates/books/review_form.html
{% extends "core/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card m-5">
    <div class="card-body">
        <h3 class="mb-3">{{ book.title }}</h3>
        {% crispy form %}
    </div>
</div>
{% endblock %}